---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: helloapp.dev.tap
  namespace: test
spec:
  serviceAccountName: default
  packageRef:
    refName: helloapp.dev.tap
    versionSelection:
      constraints: "20230309184314.0.0"
  values:
  - secretRef:
      name: dev-values
