---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: helloapp.dev.tap
  namespace: dev
spec:
  serviceAccountName: default
  packageRef:
    refName: helloapp.dev.tap
    versionSelection:
      constraints: "20230309184314.0.0"
  values:
  - secretRef:
      name: dev-values
---
apiVersion: v1
kind: Secret
metadata:
  name: dev-values
  namespace: dev
stringData:
  values.yml: |
    ---
    replicas: 2
    hostname: 35.245.126.176.nip.io