apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: test1.default.vmware.com.20230331161439.0.0
spec:
  refName: test1.default.vmware.com
  version: 20230331161439.0.0
  releaseNotes: |
    Release v20230331161439.0.0 of package test1.default.vmware.com
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: gcr.io/nziada-tkg-dev/alm-sample/test1-default-bundle@sha256:4880f10c63be6840aa34a154f4ffb757fb281fa786ca98c52801deb0adf04863
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}

