apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: dev.default.vmware.com.20230612163120.0.0+build.a5c7628
spec:
  refName: dev.default.vmware.com
  version: 20230612163120.0.0+build.a5c7628
  releaseNotes: |
    Release v20230612163120.0.0+build.a5c7628 of package dev.default.vmware.com
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: gcr.io/nziada-tkg-dev/alm-sample/dev-default-bundle@sha256:e4521fe354264221f66ba7a8c1087d131db39044e3386121d79a7eff1297cc24
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}

